/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.KhachHang;

/**
 *
 * @author TechCare
 */
public class KhachHangJPanel extends javax.swing.JPanel {

        /**
         * Creates new form KhachHangJPanel
         */
        public KhachHangJPanel() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel32 = new javax.swing.JPanel();
        jButtonXoa32 = new javax.swing.JButton();
        jLabelQLKH32 = new javax.swing.JLabel();
        jLabel2MaKH39 = new javax.swing.JLabel();
        jComboBoxGioiTinh32 = new javax.swing.JComboBox<>();
        jLabel2MaKH33 = new javax.swing.JLabel();
        jButtonThem32 = new javax.swing.JButton();
        jTextFieldMaKH36 = new javax.swing.JTextField();
        jLabel2MaKH32 = new javax.swing.JLabel();
        jButtonLuu32 = new javax.swing.JButton();
        jTextFieldMaKH32 = new javax.swing.JTextField();
        jLabel2MaKH37 = new javax.swing.JLabel();
        jLabel2MaKH34 = new javax.swing.JLabel();
        jTextFieldMaKH33 = new javax.swing.JTextField();
        jTextFieldMaKH35 = new javax.swing.JTextField();
        jButtonSearch32 = new javax.swing.JButton();
        jLabel2MaKH38 = new javax.swing.JLabel();
        jTextFieldChiTieuTu32 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAll32 = new javax.swing.JTable();
        jTextFieldMaKH34 = new javax.swing.JTextField();
        jLabel2MaKH35 = new javax.swing.JLabel();
        jTextFieldDen32 = new javax.swing.JTextField();
        jLabel2MaKH36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 219, 137));

        jPanel32.setBackground(new java.awt.Color(245, 219, 137));

        jButtonXoa32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonXoa32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonXoa32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXoa32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        jButtonXoa32.setText("Xóa");
        jButtonXoa32.setBorder(null);
        jButtonXoa32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonXoa32.setFocusPainted(false);

        jLabelQLKH32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQLKH32.setForeground(new java.awt.Color(102, 51, 0));
        jLabelQLKH32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQLKH32.setText("QUẢN LÍ KHÁCH HÀNG");

        jLabel2MaKH39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH39.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH39.setText("Đến:");

        jComboBoxGioiTinh32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxGioiTinh32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn giới tính", "Nam", "Nữ" }));

        jLabel2MaKH33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH33.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH33.setText("Họ đệm");

        jButtonThem32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonThem32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonThem32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThem32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        jButtonThem32.setText("Thêm");
        jButtonThem32.setBorder(null);
        jButtonThem32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem32.setFocusPainted(false);

        jTextFieldMaKH36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2MaKH32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH32.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH32.setText("Mã khách hàng");

        jButtonLuu32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonLuu32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLuu32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLuu32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        jButtonLuu32.setText("Lưu");
        jButtonLuu32.setBorder(null);
        jButtonLuu32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLuu32.setFocusPainted(false);

        jTextFieldMaKH32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2MaKH37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH37.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH37.setText("Tìm từ khóa");

        jLabel2MaKH34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH34.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH34.setText("Tên");

        jTextFieldMaKH33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldMaKH35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonSearch32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSearch32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSearch32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        jButtonSearch32.setBorder(null);
        jButtonSearch32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearch32.setFocusPainted(false);

        jLabel2MaKH38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH38.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH38.setText("Chi tiêu từ:");

        jTextFieldChiTieuTu32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTableAll32.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTableAll32.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ đệm", "Tên", "Giới tính", "Tổng chi tiêu"
            }
        ));
        jTableAll32.setGridColor(new java.awt.Color(128, 128, 128));
        jTableAll32.setSelectionBackground(new java.awt.Color(50, 154, 114));
        jTableAll32.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableAll32.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableAll32.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTableAll32);

        jTextFieldMaKH34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2MaKH35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH35.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH35.setText("Giới tính");

        jTextFieldDen32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2MaKH36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2MaKH36.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2MaKH36.setText("Tổng chi tiêu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mdi_database-refresh.png"))); // NOI18N

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel2MaKH38)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMaKH34, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2MaKH39)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDen32, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch32))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabelQLKH32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabel2MaKH37)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldMaKH36, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel2MaKH35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGioiTinh32, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addComponent(jLabel2MaKH33)
                                        .addGap(66, 66, 66)
                                        .addComponent(jTextFieldChiTieuTu32, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addComponent(jLabel2MaKH32)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMaKH35, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel2MaKH34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMaKH32, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel2MaKH36)
                                    .addGap(33, 33, 33)
                                    .addComponent(jTextFieldMaKH33)))))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jButtonThem32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLuu32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoa32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelQLKH32)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2MaKH32)
                    .addComponent(jTextFieldMaKH35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2MaKH33)
                    .addComponent(jTextFieldChiTieuTu32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2MaKH34)
                    .addComponent(jTextFieldMaKH32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2MaKH35)
                    .addComponent(jComboBoxGioiTinh32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2MaKH36)
                    .addComponent(jTextFieldMaKH33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem32)
                    .addComponent(jButtonLuu32)
                    .addComponent(jButtonXoa32))
                .addGap(18, 18, 18)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2MaKH37)
                    .addComponent(jTextFieldMaKH36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2MaKH38)
                        .addComponent(jTextFieldMaKH34, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2MaKH39)
                        .addComponent(jTextFieldDen32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSearch32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLuu32;
    private javax.swing.JButton jButtonSearch32;
    private javax.swing.JButton jButtonThem32;
    private javax.swing.JButton jButtonXoa32;
    private javax.swing.JComboBox<String> jComboBoxGioiTinh32;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2MaKH32;
    private javax.swing.JLabel jLabel2MaKH33;
    private javax.swing.JLabel jLabel2MaKH34;
    private javax.swing.JLabel jLabel2MaKH35;
    private javax.swing.JLabel jLabel2MaKH36;
    private javax.swing.JLabel jLabel2MaKH37;
    private javax.swing.JLabel jLabel2MaKH38;
    private javax.swing.JLabel jLabel2MaKH39;
    private javax.swing.JLabel jLabelQLKH32;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAll32;
    private javax.swing.JTextField jTextFieldChiTieuTu32;
    private javax.swing.JTextField jTextFieldDen32;
    private javax.swing.JTextField jTextFieldMaKH32;
    private javax.swing.JTextField jTextFieldMaKH33;
    private javax.swing.JTextField jTextFieldMaKH34;
    private javax.swing.JTextField jTextFieldMaKH35;
    private javax.swing.JTextField jTextFieldMaKH36;
    // End of variables declaration//GEN-END:variables
}
