package view.BanHang;

import bus.KhachHangBUS;
import custom.MyTable;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import model.KhachHang;

/**
 *
 * @author leanh
 */
public class TimKhachJDialog extends javax.swing.JDialog {

        /**
         * Creates new form TimKhachJDialog
         */
        private DefaultTableModel dtmKhachHang;
        private KhachHangBUS khBUS;
        private DecimalFormat dcf;
        public static KhachHang khachHangTimDuoc = null;

        public TimKhachJDialog() {
                initComponents();

                this.setSize(500, 400);
                this.setModal(true);
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                this.setLocationRelativeTo(null);

                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                dcf = new DecimalFormat("###,###");
                khBUS = new KhachHangBUS();

                new MyTable(jTableKhachHang62);
                dtmKhachHang = new DefaultTableModel() {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                                return false;
                        }
                };
                jTableKhachHang62.setModel(dtmKhachHang);

                dtmKhachHang.addColumn("Mã KH");
                dtmKhachHang.addColumn("Họ");
                dtmKhachHang.addColumn("Tên");
                dtmKhachHang.addColumn("Giới tính");
                dtmKhachHang.addColumn("Tổng chi tiêu");

                jTableKhachHang62.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                jTableKhachHang62.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                jTableKhachHang62.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                jTableKhachHang62.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
                jTableKhachHang62.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
                TableColumnModel columnModelKhachHang = jTableKhachHang62.getColumnModel();
                columnModelKhachHang.getColumn(0).setPreferredWidth(77);
                columnModelKhachHang.getColumn(1).setPreferredWidth(150);
                columnModelKhachHang.getColumn(2).setPreferredWidth(110);
                columnModelKhachHang.getColumn(3).setPreferredWidth(110);
                columnModelKhachHang.getColumn(4).setPreferredWidth(150);

                loadDataLenTable();
        }

        private void loadDataLenTable() {
                dtmKhachHang.setRowCount(0);
                ArrayList<KhachHang> dskh = khBUS.getListKhachHang();
                if (dskh != null) {
                        for (KhachHang kh : dskh) {
                                Vector vec = new Vector();
                                vec.add(kh.getMaKH());
                                vec.add(kh.getHo());
                                vec.add(kh.getTen());
                                vec.add(kh.getGioiTinh());
                                vec.add(kh.getTongChiTieu());
                                dtmKhachHang.addRow(vec);
                        }
                }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelView62 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextFieldTimKiem62 = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTableKhachHang62 = new javax.swing.JTable();
                jButtonChon62 = new javax.swing.JButton();
                jButtonThem62 = new javax.swing.JButton();

                setTitle("Chọn khách hàng");
                setResizable(false);
                setSize(new java.awt.Dimension(500, 360));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanelView62.setPreferredSize(new java.awt.Dimension(500, 360));
                jPanelView62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(102, 51, 0));
                jLabel1.setText("Tìm Kiếm");
                jPanelView62.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

                jTextFieldTimKiem62.setBackground(new java.awt.Color(255, 255, 255));
                jTextFieldTimKiem62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jTextFieldTimKiem62.setForeground(new java.awt.Color(0, 0, 0));
                jTextFieldTimKiem62.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jTextFieldTimKiem62KeyPressed(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                jTextFieldTimKiem62KeyReleased(evt);
                        }
                });
                jPanelView62.add(jTextFieldTimKiem62, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, -1));

                jTableKhachHang62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jTableKhachHang62.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTableKhachHang62);

                jPanelView62.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 500, 280));

                jButtonChon62.setBackground(new java.awt.Color(255, 153, 0));
                jButtonChon62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jButtonChon62.setForeground(new java.awt.Color(255, 255, 255));
                jButtonChon62.setText("OK");
                jButtonChon62.setBorder(null);
                jButtonChon62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jButtonChon62.setFocusPainted(false);
                jButtonChon62.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonChon62ActionPerformed(evt);
                        }
                });
                jPanelView62.add(jButtonChon62, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 325, 100, 30));

                jButtonThem62.setBackground(new java.awt.Color(255, 153, 0));
                jButtonThem62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jButtonThem62.setForeground(new java.awt.Color(255, 255, 255));
                jButtonThem62.setText("+ Thêm Khách");
                jButtonThem62.setBorder(null);
                jButtonThem62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jButtonThem62.setFocusPainted(false);
                jButtonThem62.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonThem62ActionPerformed(evt);
                        }
                });
                jPanelView62.add(jButtonThem62, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 5, 100, 30));

                getContentPane().add(jPanelView62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void jButtonThem62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThem62ActionPerformed
                // TODO add your handling code here:
                ThemKhachJDialog dlg = new ThemKhachJDialog();
                dlg.setVisible(true);
                if (dlg.checkThemKhach) {
                        khBUS.docDanhSach();
                        loadDataLenTable();
                }
        }//GEN-LAST:event_jButtonThem62ActionPerformed

        private void jButtonChon62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChon62ActionPerformed
                // TODO add your handling code here:
                int row = jTableKhachHang62.getSelectedRow();
                if (row > -1) {
                        int ma = Integer.parseInt(jTableKhachHang62.getValueAt(row, 0) + "");
                        String ho = jTableKhachHang62.getValueAt(row, 1) + "";
                        String ten = jTableKhachHang62.getValueAt(row, 2) + "";
                        String gioiTinh = jTableKhachHang62.getValueAt(row, 3) + "";
                        int tongChiTieu = Integer.parseInt(jTableKhachHang62.getValueAt(row, 4) + "");

                        khachHangTimDuoc = new KhachHang(ma, ho, ten, gioiTinh, tongChiTieu);
                }
                this.dispose();
        }//GEN-LAST:event_jButtonChon62ActionPerformed

        private void jTextFieldTimKiem62KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTimKiem62KeyPressed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldTimKiem62KeyPressed

        private void jTextFieldTimKiem62KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTimKiem62KeyReleased
                // TODO add your handling code here:
                searchTable(jTextFieldTimKiem62.getText());
        }//GEN-LAST:event_jTextFieldTimKiem62KeyReleased

        public void searchTable(String value) {
                TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtmKhachHang);
                jTableKhachHang62.setRowSorter(trs);
                trs.setRowFilter(RowFilter.regexFilter(value));
        }
        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonChon62;
        private javax.swing.JButton jButtonThem62;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanelView62;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTableKhachHang62;
        private javax.swing.JTextField jTextFieldTimKiem62;
        // End of variables declaration//GEN-END:variables
}
