/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.NhanVien;

/**
 *
 * @author Admin
 */
public class NhanVienJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienJPanel
     */
    public NhanVienJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NhanVienViewjPanel50 = new javax.swing.JPanel();
        NhanVienjLabel50 = new javax.swing.JLabel();
        MaNVjLabel50 = new javax.swing.JLabel();
        MaNVjTextField50 = new javax.swing.JTextField();
        HodemNVjLabel50 = new javax.swing.JLabel();
        HodemNVjTextField50 = new javax.swing.JTextField();
        TenNVNVjLabel50 = new javax.swing.JLabel();
        TenNVjTextField50 = new javax.swing.JTextField();
        GioiNVNVjLabel50 = new javax.swing.JLabel();
        GioiNVjTextField50 = new javax.swing.JTextField();
        RoleNVNVjLabel50 = new javax.swing.JLabel();
        RoleNVjTextField50 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListNVjTable50 = new javax.swing.JTable();
        AddjButton50 = new javax.swing.JButton();
        SavejButton50 = new javax.swing.JButton();
        DeljButton50 = new javax.swing.JButton();
        SearchjButton50 = new javax.swing.JButton();
        CapjButton50 = new javax.swing.JButton();
        QuyenjButton50 = new javax.swing.JButton();
        KhoajButton50 = new javax.swing.JButton();
        imgjLabel50 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1110, 630));
        setPreferredSize(new java.awt.Dimension(1200, 655));

        NhanVienViewjPanel50.setBackground(new java.awt.Color(245, 219, 137));
        NhanVienViewjPanel50.setMinimumSize(new java.awt.Dimension(1110, 630));
        NhanVienViewjPanel50.setPreferredSize(new java.awt.Dimension(1200, 655));

        NhanVienjLabel50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhanVienjLabel50.setForeground(new java.awt.Color(102, 51, 0));
        NhanVienjLabel50.setText("Quản lý nhân viên");

        MaNVjLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaNVjLabel50.setForeground(new java.awt.Color(102, 51, 0));
        MaNVjLabel50.setText("Quản lý nhân viên");

        MaNVjTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaNVjTextField50ActionPerformed(evt);
            }
        });

        HodemNVjLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HodemNVjLabel50.setForeground(new java.awt.Color(102, 51, 0));
        HodemNVjLabel50.setText("Họ đệm");

        HodemNVjTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HodemNVjTextField50ActionPerformed(evt);
            }
        });

        TenNVNVjLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TenNVNVjLabel50.setForeground(new java.awt.Color(102, 51, 0));
        TenNVNVjLabel50.setText("Tên ");

        TenNVjTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenNVjTextField50ActionPerformed(evt);
            }
        });

        GioiNVNVjLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GioiNVNVjLabel50.setForeground(new java.awt.Color(102, 51, 0));
        GioiNVNVjLabel50.setText("Giới tính");

        GioiNVjTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GioiNVjTextField50ActionPerformed(evt);
            }
        });

        RoleNVNVjLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RoleNVNVjLabel50.setForeground(new java.awt.Color(102, 51, 0));
        RoleNVNVjLabel50.setText("Chức Vụ");

        RoleNVjTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleNVjTextField50ActionPerformed(evt);
            }
        });

        ListNVjTable50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ListNVjTable50.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ ", "Tên", "Giới tính", "Chức vụ"
            }
        ));
        jScrollPane1.setViewportView(ListNVjTable50);

        AddjButton50.setBackground(new java.awt.Color(255, 153, 0));
        AddjButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddjButton50.setForeground(new java.awt.Color(255, 255, 255));
        AddjButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        AddjButton50.setText("Thêm");
        AddjButton50.setBorder(null);
        AddjButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddjButton50.setFocusPainted(false);

        SavejButton50.setBackground(new java.awt.Color(255, 153, 0));
        SavejButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SavejButton50.setForeground(new java.awt.Color(255, 255, 255));
        SavejButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        SavejButton50.setText("Lưu");
        SavejButton50.setBorder(null);
        SavejButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SavejButton50.setFocusPainted(false);

        DeljButton50.setBackground(new java.awt.Color(255, 153, 0));
        DeljButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DeljButton50.setForeground(new java.awt.Color(255, 255, 255));
        DeljButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        DeljButton50.setText("Xóa");
        DeljButton50.setBorder(null);
        DeljButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeljButton50.setFocusPainted(false);

        SearchjButton50.setBackground(new java.awt.Color(255, 153, 0));
        SearchjButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchjButton50.setForeground(new java.awt.Color(255, 255, 255));
        SearchjButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        SearchjButton50.setText("Tìm kiếm");
        SearchjButton50.setBorder(null);
        SearchjButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchjButton50.setFocusPainted(false);

        CapjButton50.setBackground(new java.awt.Color(255, 153, 0));
        CapjButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CapjButton50.setForeground(new java.awt.Color(255, 255, 255));
        CapjButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_account_circle_white_24dp.png"))); // NOI18N
        CapjButton50.setText("Cấp tài khoản");
        CapjButton50.setBorder(null);
        CapjButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CapjButton50.setFocusPainted(false);

        QuyenjButton50.setBackground(new java.awt.Color(255, 153, 0));
        QuyenjButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QuyenjButton50.setForeground(new java.awt.Color(255, 255, 255));
        QuyenjButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_admin_panel_settings_white_24dp.png"))); // NOI18N
        QuyenjButton50.setText("Mật khẩu/ Quyền");
        QuyenjButton50.setBorder(null);
        QuyenjButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuyenjButton50.setFocusPainted(false);

        KhoajButton50.setBackground(new java.awt.Color(255, 153, 0));
        KhoajButton50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KhoajButton50.setForeground(new java.awt.Color(255, 255, 255));
        KhoajButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_lock_white_24dp.png"))); // NOI18N
        KhoajButton50.setText("Khóa tài khoản");
        KhoajButton50.setBorder(null);
        KhoajButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KhoajButton50.setFocusPainted(false);

        imgjLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mdi_database-refresh.png"))); // NOI18N

        javax.swing.GroupLayout NhanVienViewjPanel50Layout = new javax.swing.GroupLayout(NhanVienViewjPanel50);
        NhanVienViewjPanel50.setLayout(NhanVienViewjPanel50Layout);
        NhanVienViewjPanel50Layout.setHorizontalGroup(
            NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                                .addComponent(RoleNVNVjLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RoleNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                                .addComponent(GioiNVNVjLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GioiNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                                .addComponent(TenNVNVjLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TenNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienViewjPanel50Layout.createSequentialGroup()
                                .addComponent(HodemNVjLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HodemNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienViewjPanel50Layout.createSequentialGroup()
                                .addComponent(MaNVjLabel50)
                                .addGap(56, 56, 56)
                                .addComponent(MaNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(CapjButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(QuyenjButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(KhoajButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienViewjPanel50Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienViewjPanel50Layout.createSequentialGroup()
                        .addComponent(NhanVienjLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgjLabel50)
                        .addGap(433, 433, 433))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienViewjPanel50Layout.createSequentialGroup()
                        .addComponent(AddjButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(SavejButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(DeljButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(SearchjButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))))
        );
        NhanVienViewjPanel50Layout.setVerticalGroup(
            NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienViewjPanel50Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NhanVienjLabel50)
                    .addComponent(imgjLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNVjLabel50)
                    .addComponent(MaNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HodemNVjLabel50)
                    .addComponent(HodemNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenNVNVjLabel50)
                    .addComponent(TenNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GioiNVNVjLabel50)
                    .addComponent(GioiNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleNVNVjLabel50)
                    .addComponent(RoleNVjTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddjButton50)
                    .addComponent(SavejButton50)
                    .addComponent(DeljButton50)
                    .addComponent(SearchjButton50))
                .addGap(18, 18, 18)
                .addGroup(NhanVienViewjPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapjButton50)
                    .addComponent(QuyenjButton50)
                    .addComponent(KhoajButton50))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhanVienViewjPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhanVienViewjPanel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaNVjTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaNVjTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaNVjTextField50ActionPerformed

    private void HodemNVjTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HodemNVjTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HodemNVjTextField50ActionPerformed

    private void TenNVjTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenNVjTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenNVjTextField50ActionPerformed

    private void GioiNVjTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GioiNVjTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GioiNVjTextField50ActionPerformed

    private void RoleNVjTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleNVjTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleNVjTextField50ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddjButton50;
    private javax.swing.JButton CapjButton50;
    private javax.swing.JButton DeljButton50;
    private javax.swing.JLabel GioiNVNVjLabel50;
    private javax.swing.JTextField GioiNVjTextField50;
    private javax.swing.JLabel HodemNVjLabel50;
    private javax.swing.JTextField HodemNVjTextField50;
    private javax.swing.JButton KhoajButton50;
    private javax.swing.JTable ListNVjTable50;
    private javax.swing.JLabel MaNVjLabel50;
    private javax.swing.JTextField MaNVjTextField50;
    private javax.swing.JPanel NhanVienViewjPanel50;
    private javax.swing.JLabel NhanVienjLabel50;
    private javax.swing.JButton QuyenjButton50;
    private javax.swing.JLabel RoleNVNVjLabel50;
    private javax.swing.JTextField RoleNVjTextField50;
    private javax.swing.JButton SavejButton50;
    private javax.swing.JButton SearchjButton50;
    private javax.swing.JLabel TenNVNVjLabel50;
    private javax.swing.JTextField TenNVjTextField50;
    private javax.swing.JLabel imgjLabel50;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
