/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.SanPham;

/**
 *
 * @author TechCare
 */
public class SanPhamJPanel extends javax.swing.JPanel {

        /**
         * Creates new form SanPhamJPanel
         */
        public SanPhamJPanel() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel32 = new javax.swing.JPanel();
        jLabelQLSP32 = new javax.swing.JLabel();
        jLabelMaSP32 = new javax.swing.JLabel();
        jTextFieldMaSP32 = new javax.swing.JTextField();
        jLabelMaSP36 = new javax.swing.JLabel();
        jTextFieldMaSP33 = new javax.swing.JTextField();
        jLabelMaSP37 = new javax.swing.JLabel();
        jComboBoxLoai32 = new javax.swing.JComboBox<>();
        jLabelMaSP34 = new javax.swing.JLabel();
        jLabelMaSP38 = new javax.swing.JLabel();
        jTextFieldMaSP35 = new javax.swing.JTextField();
        jTextFieldMaSP36 = new javax.swing.JTextField();
        jLabelMaSP39 = new javax.swing.JLabel();
        jLabelMaSP40 = new javax.swing.JLabel();
        jTextFieldMaSP37 = new javax.swing.JTextField();
        jButtonThem32 = new javax.swing.JButton();
        jButtonLuu32 = new javax.swing.JButton();
        jButtonXoa32 = new javax.swing.JButton();
        jButtonTimKiem32 = new javax.swing.JButton();
        jButtonChonAnh32 = new javax.swing.JButton();
        jLabelImage32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAll32 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMaSP38 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(245, 219, 137));
        setPreferredSize(new java.awt.Dimension(1200, 655));

        jPanel32.setBackground(new java.awt.Color(245, 219, 137));
        jPanel32.setPreferredSize(new java.awt.Dimension(1200, 655));

        jLabelQLSP32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQLSP32.setForeground(new java.awt.Color(102, 51, 0));
        jLabelQLSP32.setText("QUẢN LÝ SẢN PHẨM");

        jLabelMaSP32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP32.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP32.setText("Mã SP ");

        jTextFieldMaSP32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMaSP32.setForeground(new java.awt.Color(255, 255, 255));

        jLabelMaSP36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP36.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP36.setText("Tên SP ");

        jTextFieldMaSP33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMaSP33.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldMaSP33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSP33ActionPerformed(evt);
            }
        });

        jLabelMaSP37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP37.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP37.setText("Loại");

        jComboBoxLoai32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxLoai32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelMaSP34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP34.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP34.setText("Số Lượng");

        jLabelMaSP38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP38.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP38.setText("Đơn vị tính");

        jTextFieldMaSP35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMaSP35.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldMaSP36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMaSP36.setForeground(new java.awt.Color(255, 255, 255));

        jLabelMaSP39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP39.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP39.setText("Đơn giá");

        jLabelMaSP40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMaSP40.setForeground(new java.awt.Color(102, 51, 0));
        jLabelMaSP40.setText("Từ khóa tìm");

        jTextFieldMaSP37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMaSP37.setForeground(new java.awt.Color(255, 255, 255));

        jButtonThem32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonThem32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonThem32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThem32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        jButtonThem32.setText("Thêm");
        jButtonThem32.setBorder(null);
        jButtonThem32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThem32.setFocusPainted(false);

        jButtonLuu32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonLuu32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLuu32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLuu32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        jButtonLuu32.setText("Lưu");
        jButtonLuu32.setBorder(null);
        jButtonLuu32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLuu32.setFocusPainted(false);

        jButtonXoa32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonXoa32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonXoa32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXoa32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        jButtonXoa32.setText("Xóa");
        jButtonXoa32.setBorder(null);
        jButtonXoa32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonXoa32.setFocusPainted(false);

        jButtonTimKiem32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonTimKiem32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTimKiem32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimKiem32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        jButtonTimKiem32.setText("Tìm kiếm");
        jButtonTimKiem32.setBorder(null);
        jButtonTimKiem32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTimKiem32.setFocusPainted(false);

        jButtonChonAnh32.setBackground(new java.awt.Color(255, 153, 0));
        jButtonChonAnh32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChonAnh32.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChonAnh32.setText("Chọn ảnh");
        jButtonChonAnh32.setBorder(null);
        jButtonChonAnh32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChonAnh32.setFocusPainted(false);

        jLabelImage32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelImage32.setForeground(new java.awt.Color(102, 51, 0));
        jLabelImage32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage32.setText("IMAGE");

        jTableAll32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableAll32.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Đơn giá", "Số lượng", "Đơn vị tính", "Đơn giá"
            }
        ));
        jTableAll32.setPreferredSize(new java.awt.Dimension(300, 100));
        jScrollPane1.setViewportView(jTableAll32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mdi_database-refresh.png"))); // NOI18N

        jTextFieldMaSP38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldMaSP38.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelQLSP32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(456, 456, 456))
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabelMaSP40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaSP35, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButtonThem32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLuu32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonXoa32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTimKiem32, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMaSP38)
                                    .addComponent(jLabelMaSP39)
                                    .addComponent(jLabelMaSP34)
                                    .addComponent(jLabelMaSP32)
                                    .addComponent(jLabelMaSP36)
                                    .addComponent(jLabelMaSP37))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMaSP32)
                                    .addComponent(jTextFieldMaSP36)
                                    .addComponent(jTextFieldMaSP38)
                                    .addComponent(jComboBoxLoai32, 0, 250, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMaSP33)
                                    .addComponent(jTextFieldMaSP37))
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(jLabelImage32))
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jButtonChonAnh32))))))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabelImage32)
                                .addGap(56, 56, 56)
                                .addComponent(jButtonChonAnh32)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabelQLSP32)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addComponent(jLabelMaSP32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelMaSP36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMaSP37))
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addComponent(jTextFieldMaSP37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMaSP33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxLoai32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaSP34)
                                    .addComponent(jTextFieldMaSP32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaSP39)
                                    .addComponent(jTextFieldMaSP36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMaSP38)
                                    .addComponent(jTextFieldMaSP38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(199, 199, 199)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaSP40)
                    .addComponent(jTextFieldMaSP35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLuu32)
                    .addComponent(jButtonXoa32)
                    .addComponent(jButtonTimKiem32)
                    .addComponent(jButtonThem32))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMaSP33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSP33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSP33ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChonAnh32;
    private javax.swing.JButton jButtonLuu32;
    private javax.swing.JButton jButtonThem32;
    private javax.swing.JButton jButtonTimKiem32;
    private javax.swing.JButton jButtonXoa32;
    private javax.swing.JComboBox<String> jComboBoxLoai32;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImage32;
    private javax.swing.JLabel jLabelMaSP32;
    private javax.swing.JLabel jLabelMaSP34;
    private javax.swing.JLabel jLabelMaSP36;
    private javax.swing.JLabel jLabelMaSP37;
    private javax.swing.JLabel jLabelMaSP38;
    private javax.swing.JLabel jLabelMaSP39;
    private javax.swing.JLabel jLabelMaSP40;
    private javax.swing.JLabel jLabelQLSP32;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAll32;
    private javax.swing.JTextField jTextFieldMaSP32;
    private javax.swing.JTextField jTextFieldMaSP33;
    private javax.swing.JTextField jTextFieldMaSP35;
    private javax.swing.JTextField jTextFieldMaSP36;
    private javax.swing.JTextField jTextFieldMaSP37;
    private javax.swing.JTextField jTextFieldMaSP38;
    // End of variables declaration//GEN-END:variables
}
