package view.HoaDon;

/**
 *
 * @author leanh
 */
public class HoaDonJPanel extends javax.swing.JPanel {

        /**
         * Creates new form HoaDonJPanel
         */
        public HoaDonJPanel() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanelView62 = new javax.swing.JPanel();
                jPanelCTHD36 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTableCTHoaDon36 = new javax.swing.JTable();
                jLabelCTSP36 = new javax.swing.JLabel();
                jPanelTTCTHD37 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jTextFieldMaHDct36 = new javax.swing.JTextField();
                jTextFieldTenSPct36 = new javax.swing.JTextField();
                jTextFieldSoLuong36 = new javax.swing.JTextField();
                jTextFieldDonGia36 = new javax.swing.JTextField();
                jTextFieldThanhTien36 = new javax.swing.JTextField();
                jPanelTTHD36 = new javax.swing.JPanel();
                jPanelTTCTHD36 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jTextFieldMaHD36 = new javax.swing.JTextField();
                jTextFieldMaKH36 = new javax.swing.JTextField();
                jTextFieldMaNV36 = new javax.swing.JTextField();
                jTextFieldNgayLap36 = new javax.swing.JTextField();
                jTextFieldTongTien36 = new javax.swing.JTextField();
                jTextFieldGhiChu36 = new javax.swing.JTextField();
                jLabelDSSP36 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jListHoaDon36 = new javax.swing.JList<>();
                jPanel1 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jTextFieldDonGiaFrom36 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jTextFieldDonGiaTo36 = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                jTextFieldNgayFrom36 = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();
                jTextFieldNgayTo36 = new javax.swing.JTextField();

                setPreferredSize(new java.awt.Dimension(1200, 655));

                jPanelView62.setBackground(new java.awt.Color(238, 196, 70));
                jPanelView62.setMinimumSize(new java.awt.Dimension(1110, 630));
                jPanelView62.setPreferredSize(new java.awt.Dimension(1200, 655));
                jPanelView62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanelCTHD36.setBackground(new java.awt.Color(245, 219, 137));
                jPanelCTHD36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
                jPanelCTHD36.setPreferredSize(new java.awt.Dimension(580, 655));
                jPanelCTHD36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jScrollPane2.setPreferredSize(new java.awt.Dimension(580, 355));

                jTableCTHoaDon36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jTableCTHoaDon36.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jTableCTHoaDon36.setPreferredSize(new java.awt.Dimension(580, 355));
                jScrollPane2.setViewportView(jTableCTHoaDon36);

                jPanelCTHD36.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 260, 565, 400));

                jLabelCTSP36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabelCTSP36.setText("Chi tiết hóa đơn");
                jPanelCTHD36.add(jLabelCTSP36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 15, -1, -1));

                jPanelTTCTHD37.setBackground(new java.awt.Color(245, 219, 137));

                jLabel12.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel12.setText("Mã hóa đơn");

                jLabel13.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel13.setText("Thành tiền");

                jLabel14.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel14.setText("Sản phẩm");

                jLabel15.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel15.setText("Số lượng");

                jLabel16.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel16.setText("Đơn giá");

                jTextFieldMaHDct36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldMaHDct36.setEnabled(false);

                jTextFieldTenSPct36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldTenSPct36.setEnabled(false);

                jTextFieldSoLuong36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldSoLuong36.setEnabled(false);
                jTextFieldSoLuong36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldSoLuong36ActionPerformed(evt);
                        }
                });

                jTextFieldDonGia36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldDonGia36.setEnabled(false);
                jTextFieldDonGia36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldDonGia36ActionPerformed(evt);
                        }
                });

                jTextFieldThanhTien36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldThanhTien36.setEnabled(false);
                jTextFieldThanhTien36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldThanhTien36ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanelTTCTHD37Layout = new javax.swing.GroupLayout(jPanelTTCTHD37);
                jPanelTTCTHD37.setLayout(jPanelTTCTHD37Layout);
                jPanelTTCTHD37Layout.setHorizontalGroup(
                        jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTTCTHD37Layout.createSequentialGroup()
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel14))
                                        .addGroup(jPanelTTCTHD37Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel13)))
                                .addGap(38, 38, 38)
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldThanhTien36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMaHDct36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTenSPct36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSoLuong36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDonGia36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                );
                jPanelTTCTHD37Layout.setVerticalGroup(
                        jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTTCTHD37Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMaHDct36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldTenSPct36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldSoLuong36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldDonGia36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldThanhTien36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13))
                                .addContainerGap(13, Short.MAX_VALUE))
                );

                jPanelCTHD36.add(jPanelTTCTHD37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 360, 210));

                jPanelView62.add(jPanelCTHD36, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, -5, 590, 660));

                jPanelTTHD36.setBackground(new java.awt.Color(245, 219, 137));
                jPanelTTHD36.setPreferredSize(new java.awt.Dimension(623, 655));
                jPanelTTHD36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanelTTCTHD36.setBackground(new java.awt.Color(245, 219, 137));

                jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel2.setText("Mã hóa đơn");

                jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel6.setText("Tổng tiền");

                jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel3.setText("Mã khách hàng");

                jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel4.setText("Mã nhân viên");

                jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel5.setText("Ngày");

                jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel7.setText("Ghi chú");

                jTextFieldMaHD36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldMaHD36.setEnabled(false);
                jTextFieldMaHD36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldMaHD36ActionPerformed(evt);
                        }
                });

                jTextFieldMaKH36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldMaKH36.setEnabled(false);

                jTextFieldMaNV36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldMaNV36.setEnabled(false);
                jTextFieldMaNV36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldMaNV36ActionPerformed(evt);
                        }
                });

                jTextFieldNgayLap36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldNgayLap36.setEnabled(false);
                jTextFieldNgayLap36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldNgayLap36ActionPerformed(evt);
                        }
                });

                jTextFieldTongTien36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldTongTien36.setEnabled(false);
                jTextFieldTongTien36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldTongTien36ActionPerformed(evt);
                        }
                });

                jTextFieldGhiChu36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldGhiChu36.setEnabled(false);
                jTextFieldGhiChu36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldGhiChu36ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanelTTCTHD36Layout = new javax.swing.GroupLayout(jPanelTTCTHD36);
                jPanelTTCTHD36.setLayout(jPanelTTCTHD36Layout);
                jPanelTTCTHD36Layout.setHorizontalGroup(
                        jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTTCTHD36Layout.createSequentialGroup()
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldMaHD36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMaKH36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMaNV36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTongTien36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNgayLap36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldGhiChu36, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                );
                jPanelTTCTHD36Layout.setVerticalGroup(
                        jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTTCTHD36Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMaHD36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMaKH36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldMaNV36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldNgayLap36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldTongTien36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTTCTHD36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldGhiChu36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addContainerGap(10, Short.MAX_VALUE))
                );

                jPanelTTHD36.add(jPanelTTCTHD36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 380, 220));

                jLabelDSSP36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabelDSSP36.setText("Thông tin hóa đơn");
                jPanelTTHD36.add(jLabelDSSP36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

                jListHoaDon36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jListHoaDon36.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane1.setViewportView(jListHoaDon36);

                jPanelTTHD36.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, 621, 280));

                jPanel1.setBackground(new java.awt.Color(245, 219, 137));

                jLabel8.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel8.setText("Giá từ:");

                jTextFieldDonGiaFrom36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldDonGiaFrom36.setEnabled(false);
                jTextFieldDonGiaFrom36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldDonGiaFrom36ActionPerformed(evt);
                        }
                });

                jLabel10.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel10.setText("đến:");

                jTextFieldDonGiaTo36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldDonGiaTo36.setEnabled(false);
                jTextFieldDonGiaTo36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldDonGiaTo36ActionPerformed(evt);
                        }
                });

                jLabel9.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel9.setText("Ngày từ:");

                jTextFieldNgayFrom36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldNgayFrom36.setEnabled(false);
                jTextFieldNgayFrom36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldNgayFrom36ActionPerformed(evt);
                        }
                });

                jLabel11.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
                jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel11.setText("đến:");

                jTextFieldNgayTo36.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
                jTextFieldNgayTo36.setEnabled(false);
                jTextFieldNgayTo36.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldNgayTo36ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldDonGiaFrom36, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldNgayFrom36, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldDonGiaTo36, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldNgayTo36, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldDonGiaTo36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldDonGiaFrom36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldNgayTo36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextFieldNgayFrom36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanelTTHD36.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 530, 90));

                jPanelView62.add(jPanelTTHD36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 623, 655));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1200, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanelView62, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 655, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanelView62, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jTextFieldMaNV36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaNV36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldMaNV36ActionPerformed

        private void jTextFieldTongTien36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTongTien36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldTongTien36ActionPerformed

        private void jTextFieldNgayLap36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayLap36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldNgayLap36ActionPerformed

        private void jTextFieldGhiChu36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGhiChu36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldGhiChu36ActionPerformed

        private void jTextFieldDonGiaFrom36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDonGiaFrom36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldDonGiaFrom36ActionPerformed

        private void jTextFieldNgayFrom36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayFrom36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldNgayFrom36ActionPerformed

        private void jTextFieldDonGiaTo36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDonGiaTo36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldDonGiaTo36ActionPerformed

        private void jTextFieldNgayTo36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayTo36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldNgayTo36ActionPerformed

        private void jTextFieldSoLuong36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoLuong36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldSoLuong36ActionPerformed

        private void jTextFieldThanhTien36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldThanhTien36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldThanhTien36ActionPerformed

        private void jTextFieldDonGia36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDonGia36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldDonGia36ActionPerformed

        private void jTextFieldMaHD36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaHD36ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextFieldMaHD36ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLabel jLabelCTSP36;
        private javax.swing.JLabel jLabelDSSP36;
        private javax.swing.JList<String> jListHoaDon36;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanelCTHD36;
        private javax.swing.JPanel jPanelTTCTHD36;
        private javax.swing.JPanel jPanelTTCTHD37;
        private javax.swing.JPanel jPanelTTHD36;
        private javax.swing.JPanel jPanelView62;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTableCTHoaDon36;
        private javax.swing.JTextField jTextFieldDonGia36;
        private javax.swing.JTextField jTextFieldDonGiaFrom36;
        private javax.swing.JTextField jTextFieldDonGiaTo36;
        private javax.swing.JTextField jTextFieldGhiChu36;
        private javax.swing.JTextField jTextFieldMaHD36;
        private javax.swing.JTextField jTextFieldMaHDct36;
        private javax.swing.JTextField jTextFieldMaKH36;
        private javax.swing.JTextField jTextFieldMaNV36;
        private javax.swing.JTextField jTextFieldNgayFrom36;
        private javax.swing.JTextField jTextFieldNgayLap36;
        private javax.swing.JTextField jTextFieldNgayTo36;
        private javax.swing.JTextField jTextFieldSoLuong36;
        private javax.swing.JTextField jTextFieldTenSPct36;
        private javax.swing.JTextField jTextFieldThanhTien36;
        private javax.swing.JTextField jTextFieldTongTien36;
        // End of variables declaration//GEN-END:variables
}
